<?php
/**
 * User: keven
 * Date: 2016/10/19
 * Time: 11:59
 */

namespace common\widgets;


use common\models\BookLogic;
use yii\base\Widget;
use yii\data\ArrayDataProvider;

class Test extends Widget
{
    private $mes;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->mes === null){
            $this->mes = 'widget';
        }
    }

    public function run()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels'=>BookLogic::data(),
            'pagination'=>[
                'pageSize'=>5,
                'page'=>0,
            ],
        ]);
        return $this->render('index',[
            'dataProvider'=>$dataProvider,
        ]);
    }
}