<?php
/**
 * User: keven
 * Date: 2016/10/19
 * Time: 11:59
 */

namespace common\widgets;


use yii\base\Widget;

class Test extends Widget
{
    private $mes;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->mes === null){
            $this->mes = 'widget';
        }
    }

    public function run()
    {
        return "<h1>第一个{$this->mes}</h1>";
    }
}