-- MySQL Script generated by MySQL Workbench
-- 11/07/16 16:23:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_movie` DEFAULT CHARACTER SET utf8 ;
USE `db_movie` ;

-- -----------------------------------------------------
-- Table `db_movie`.`t_video_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_video_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '视频名称',
  `issue_date` INT UNSIGNED NULL COMMENT '出版时间',
  `play_time` INT UNSIGNED NULL COMMENT '播放时长',
  `cover_img` VARCHAR(255) NULL COMMENT '封面图片',
  `thumb_img` VARCHAR(255) NULL COMMENT '缩略图',
  `origin_url` VARCHAR(255) NOT NULL COMMENT '原始视频地址',
  `play_url` VARCHAR(255) NULL COMMENT '视频播放地址',
  `status` TINYINT(3) NOT NULL COMMENT '视频状态',
  `created_at` INT UNSIGNED NOT NULL COMMENT '创建时间',
  `updated_at` INT UNSIGNED NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movie`.`t_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '标签名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movie`.`t_video_tag_pivot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_video_tag_pivot` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL COMMENT '标签ID',
  PRIMARY KEY (`id`),
  INDEX `fk_t_video_tag_pivot__t_video_info__tag_id__id_idx` (`tag_id` ASC),
  INDEX `fk_t_video_tag_pivot__t_tag__video_id__id_idx` (`video_id` ASC),
  CONSTRAINT `fk_t_video_tag_pivot__t_video_info__tag_id__id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `db_movie`.`t_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_video_tag_pivot__t_tag__video_id__id`
    FOREIGN KEY (`video_id`)
    REFERENCES `db_movie`.`t_video_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movie`.`t_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_actor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL COMMENT '演员姓名',
  `birthdate` INT UNSIGNED NOT NULL COMMENT '出生年月',
  `intruoduce` TEXT NULL COMMENT '介绍',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movie`.`t_actor_tag_pivot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_actor_tag_pivot` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actor_id` INT UNSIGNED NOT NULL COMMENT '演员ID',
  `tag_id` INT UNSIGNED NOT NULL COMMENT '标签ID',
  PRIMARY KEY (`id`),
  INDEX `fk_t_actor_tag_pivot__t_actor__actor_id__id_idx` (`actor_id` ASC),
  INDEX `fk_t_actor_tag_pivot__t_tag__tag_id__id_idx` (`tag_id` ASC),
  CONSTRAINT `fk_t_actor_tag_pivot__t_actor__actor_id__id`
    FOREIGN KEY (`actor_id`)
    REFERENCES `db_movie`.`t_actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_actor_tag_pivot__t_tag__tag_id__id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `db_movie`.`t_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_movie`.`t_video_actor_pivot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_movie`.`t_video_actor_pivot` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_video_actor_pivot__t_video_info__video_id__id_idx` (`video_id` ASC),
  INDEX `fk_t_video_actor_pivot__t_actor__actor_id__id_idx` (`actor_id` ASC),
  CONSTRAINT `fk_t_video_actor_pivot__t_video_info__video_id__id`
    FOREIGN KEY (`video_id`)
    REFERENCES `db_movie`.`t_video_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_video_actor_pivot__t_actor__actor_id__id`
    FOREIGN KEY (`actor_id`)
    REFERENCES `db_movie`.`t_actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
